# Generated by Django 5.0.7 on 2024-09-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Country_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Country_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('Capial_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Capital_name', models.CharField(max_length=20)),
                ('Country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
