# Generated by Django 5.0.7 on 2024-11-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Not provided', max_length=15),
        ),
    ]
