# Generated by Django 5.0.7 on 2024-10-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('PC_id', models.IntegerField(primary_key=True, serialize=False)),
                ('PC_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_id', models.IntegerField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('MF_date', models.DateField()),
                ('MF_place', models.CharField(max_length=30)),
                ('PC_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
