# Generated by Django 5.0.7 on 2024-11-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_photo',
            new_name='profile_photo',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='User_name',
            new_name='username',
        ),
    ]
