# Generated by Django 5.0.7 on 2025-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
