# Generated by Django 5.0.7 on 2025-02-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_remove_department_location_alter_employee_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
